### ISSUE TITLE
Where are the ad-hoc kernels?

### ISSUE THREAD

**Issue by daviddoria** [ProjectSPAN/android-manet-manager#7]
I found this repository:

https://github.com/monk-dot/SPAN/tree/master/kernels

that seems to have the kernel necessary to run ad-hoc mode on a Nexus 7. However, on the main page (https://github.com/monk-dot/SPAN) it says the code is moved to here (https://github.com/ProjectSPAN), but I don't see any kernels here? Am I still supposed to use the one in the monk-dot/SPAN repository?

Thanks,

David

**Comment by jrobble** [comment]
David,

You found the right repo:
https://github.com/monk-dot/SPAN/tree/master/kernels

In general, the following repo is for the source code for the Android apps:
https://github.com/ProjectSPAN)
- Jeff (stoker)
